### ISSUE TITLE
Duplication of demo page between wellio & wellioviz? 

### ISSUE THREAD

**Issue by JustinGOSSES** [JustinGOSSES/wellio.js#52]
We are currently more or less duplicating the demo page between the wellio and wellioviz repositories.

This seems...inelegant. 

Should we:

**1. Continue duplication. Keep wellio demo page bare and spartan and develop wellioviz into fancier version?**
This seems somewhat logical as wellio is about conversion not visualization. But there will be pressure to make it look nicer because the other one does.

**2. Move the demo page to wellioviz and point to that location from wellio?**
Having a single page makes sense. Wellioviz needs more actual visual inspection to make sure it works where as wellio only really needs tests, not a visual representation to make sure it works.

**3. Move it to its own repository and point to it from both wellioviz & wellio?**
This has some logic in that both libraries contribute to make the demo.html page possible. 
The downside is then it becomes harder to use it as a test page for the libraries without deploying them to NPM.

**4. Duplicate it exactly in both places** via a script that copies the whole repository of one of them, deletes everything except the right files and folders and pastes into the repository where the script is running, probably wellio.js.

**Comment by dcslagel** [comment]
@JustinGOSSES,

I read through the 4 approaches.  My current thinking is a variation on #1 but instead of keeping the wellio.js page spartan it remains open to evolving focused on data conversions.  Continue the duplication in the areas of overall style and layout iterations.  Let the the two html pages evolve separately in their areas of emphasis: wellio for conversion, and wellioviz for graphic visualization.  Having both pages is helpful to their respective audiences.  

However, if one of the other 3 options is preferable, then 2 is a reasonable way to go because it reduces overall complexity.

DC
